// Ported from flying-saucer-core/src/main/java/org/xhtmlrenderer/css/parser/Lexer.flex
//
// The Java Lexer.java is generated by JFlex from Lexer.flex. This file is a
// hand-written tokenizer for the same specification rather than a
// transliteration of the generated tables. It keeps the JFlex semantics:
//
//   - at each position every rule is tried, the longest match wins and, among
//     matches of the same length, the rule that comes first in Lexer.flex wins;
//   - %ignorecase: string literals and the letter macros (A, C, D, ...) match
//     without regard to case. JFlex closes them over the Unicode simple case
//     mappings, so "k" also matches U+212A, "s" also matches U+017F and "i"
//     also matches U+0130 and U+0131;
//   - %line: YyLine is the number of line terminators before the start of the
//     current token, counted as the generated scanner counts them;
//   - Lexer.flex declares no %state, so YYINITIAL is the only lexical state.
//
// The input is held as code points (JFlex %unicode matches code points), so
// Yylength and Yycharat count code points where Java counts UTF-16 code
// units. The two agree for text in the Basic Multilingual Plane.

package ufo

import (
	"io"
)

const (
	// LexerYyeof is returned by the generated scanner's integer API at end of file.
	LexerYyeof = -1

	// LexerYyinitial is the only lexical state.
	LexerYyinitial = 0
)

type Lexer struct {
	zzReader io.Reader

	// zzBuffer holds the whole input. It is read from zzReader by the first
	// call of Yylex after the constructor or Yyreset.
	zzBuffer []rune
	zzLoaded bool

	zzLexicalState int

	// zzStartRead and zzMarkedPos delimit Yytext in zzBuffer.
	zzStartRead int
	zzMarkedPos int

	zzAtEOF bool

	yyline int
}

// lexerUnitRule is one of the {num}{letter}... rules of Lexer.flex.
type lexerUnitRule struct {
	letters string
	token   *Token
}

// lexerUnitRules lists the unit rules in the order of Lexer.flex, which
// decides between rules matching the same length.
var lexerUnitRules = []lexerUnitRule{
	{"em", TokenTkEms},
	{"ex", TokenTkExs},
	{"px", TokenTkPx},
	{"cm", TokenTkCm},
	{"mm", TokenTkMm},
	{"in", TokenTkIn},
	{"pt", TokenTkPt},
	{"pc", TokenTkPc},
	{"deg", TokenTkAngle},
	{"rad", TokenTkAngle},
	{"grad", TokenTkAngle},
	{"ms", TokenTkTime},
	{"s", TokenTkTime},
	{"hz", TokenTkFreq},
	{"khz", TokenTkFreq},
}

// NewLexer creates a new scanner reading UTF-8 text from in.
func NewLexer(in io.Reader) *Lexer {
	return &Lexer{zzReader: in, zzLexicalState: LexerYyinitial}
}

func (l *Lexer) YyLine() int {
	return l.yyline
}

func (l *Lexer) SetYyLine(i int) {
	l.yyline = i
}

// Yyclose closes the input reader. All subsequent calls of Yylex return the
// end of file token.
func (l *Lexer) Yyclose() error {
	l.zzAtEOF = true
	l.zzLoaded = true
	l.zzBuffer = l.zzBuffer[:l.zzStartRead]
	l.zzMarkedPos = l.zzStartRead
	if c, ok := l.zzReader.(io.Closer); ok {
		return c.Close()
	}
	return nil
}

// Yyreset resets the scanner to read from a new input stream. It does not
// close the old reader. All internal variables are reset, the old input
// stream cannot be reused. The lexical state is set to LexerYyinitial.
func (l *Lexer) Yyreset(reader io.Reader) {
	l.zzReader = reader
	l.zzBuffer = nil
	l.zzLoaded = false
	l.yyResetPosition()
	l.zzLexicalState = LexerYyinitial
}

func (l *Lexer) yyResetPosition() {
	l.zzAtEOF = false
	l.zzMarkedPos = 0
	l.zzStartRead = 0
	l.yyline = 0
}

// YyatEOF returns whether the scanner has reached the end of the reader it
// reads from.
func (l *Lexer) YyatEOF() bool {
	return l.zzAtEOF
}

// Yystate returns the current lexical state.
func (l *Lexer) Yystate() int {
	return l.zzLexicalState
}

// Yybegin enters a new lexical state.
func (l *Lexer) Yybegin(newState int) {
	l.zzLexicalState = newState
}

// Yytext returns the text matched by the current regular expression.
func (l *Lexer) Yytext() string {
	return string(l.zzBuffer[l.zzStartRead:l.zzMarkedPos])
}

// Yycharat returns the character at the given position from the matched
// text. position is a value from 0 to Yylength()-1.
func (l *Lexer) Yycharat(position int) rune {
	return l.zzBuffer[l.zzStartRead+position]
}

// Yylength is the length of the matched text region.
func (l *Lexer) Yylength() int {
	return l.zzMarkedPos - l.zzStartRead
}

// Yypushback pushes the specified amount of characters back into the input
// stream. They will be read again by the next call of Yylex. number must not
// be greater than Yylength().
func (l *Lexer) Yypushback(number int) {
	if number > l.Yylength() {
		panic(NewXRRuntimeException("Error: pushback value was too large"))
	}

	l.zzMarkedPos -= number
}

// zzLoad reads the whole input. The generated scanner refills a buffer from
// the reader while it scans; reading everything first gives the same tokens.
func (l *Lexer) zzLoad() error {
	if l.zzLoaded {
		return nil
	}
	var data []byte
	if l.zzReader != nil {
		var err error
		data, err = io.ReadAll(l.zzReader)
		if err != nil {
			return err
		}
	}
	l.zzBuffer = []rune(string(data))
	l.zzLoaded = true
	return nil
}

// Yylex resumes scanning until the next regular expression is matched, the
// end of input is encountered or an I/O error occurs.
func (l *Lexer) Yylex() (*Token, error) {
	if err := l.zzLoad(); err != nil {
		return nil, err
	}

	buf := l.zzBuffer
	for {
		// %line: count the line terminators of the previous match. A "\r"
		// ending the match is not counted when "\n" follows it, because that
		// "\n" completes the same line terminator.
		zzR := false
		for _, ch := range buf[l.zzStartRead:l.zzMarkedPos] {
			switch ch {
			case '\u000B', '\u000C', '\u0085', '\u2028', '\u2029':
				l.yyline++
				zzR = false
			case '\r':
				l.yyline++
				zzR = true
			case '\n':
				if zzR {
					zzR = false
				} else {
					l.yyline++
				}
			default:
				zzR = false
			}
		}
		if zzR && l.zzMarkedPos < len(buf) && buf[l.zzMarkedPos] == '\n' {
			l.yyline--
		}

		l.zzStartRead = l.zzMarkedPos

		if l.zzStartRead >= len(buf) {
			l.zzAtEOF = true
			return TokenTkEof, nil
		}

		end, token, other := l.zzMatch(l.zzStartRead)
		l.zzMarkedPos = end
		if end >= len(buf) {
			l.zzAtEOF = true
		}
		if other {
			return TokenCreateOtherToken(l.Yytext()), nil
		}
		if token == nil {
			/* ignore comments */
			continue
		}
		return token, nil
	}
}

// zzMatch applies the rules of Lexer.flex at position p, which is before the
// end of the input. It returns the end of the longest match and its token.
// The token is nil for a comment. other reports that only the last rule (".")
// matched, whose token is created from the matched text.
func (l *Lexer) zzMatch(p int) (end int, token *Token, other bool) {
	best := -1
	var bestToken *Token

	// consider records a match of a rule. Rules are considered in the order
	// of Lexer.flex, so a later rule replaces an earlier one only with a
	// longer match.
	consider := func(e int, t *Token) {
		if e > best {
			best = e
			bestToken = t
		}
	}

	c := l.zzBuffer[p]

	// {s}
	if lexerIsSpace(c) {
		consider(l.zzSpaceEnd(p), TokenTkS)
	}

	// {comment}
	if c == '/' {
		consider(l.zzComment(p), nil)
	}

	switch c {
	case '<':
		consider(l.zzLiteral(p, "<!--"), TokenTkCdo)
	case '-':
		consider(l.zzLiteral(p, "-->"), TokenTkCdc)
	case '~':
		consider(l.zzLiteral(p, "~="), TokenTkIncludes)
	case '|':
		consider(l.zzLiteral(p, "|="), TokenTkDashmatch)
	case '^':
		consider(l.zzLiteral(p, "^="), TokenTkPrefixmatch)
	case '$':
		consider(l.zzLiteral(p, "$="), TokenTkSuffixmatch)
	case '*':
		consider(l.zzLiteral(p, "*="), TokenTkSubstringmatch)
	}

	// {w}"{", {w}"+", {w}">", {w}","
	if lexerIsSpace(c) || c == '{' || c == '+' || c == '>' || c == ',' {
		q := l.zzSpaceEnd(p)
		if q < len(l.zzBuffer) {
			switch l.zzBuffer[q] {
			case '{':
				consider(q+1, TokenTkLbrace)
			case '+':
				consider(q+1, TokenTkPlus)
			case '>':
				consider(q+1, TokenTkGreater)
			case ',':
				consider(q+1, TokenTkComma)
			}
		}
	}

	// {string}, {invalid}
	if c == '"' || c == '\'' {
		e, closed := l.zzString(p)
		if closed {
			consider(e, TokenTkString)
		} else {
			/* unclosed string */
			consider(e, TokenTkInvalid)
		}
	}

	// {ident}
	identEnd := l.zzIdent(p)
	consider(identEnd, TokenTkIdent)

	// "#"{name}
	if c == '#' {
		if e := l.zzName(p + 1); e >= 0 {
			consider(e, TokenTkHash)
		}
	}

	if c == '@' {
		consider(l.zzLiteral(p, "@import"), TokenTkImportSym)
		consider(l.zzLiteral(p, "@page"), TokenTkPageSym)
		consider(l.zzLiteral(p, "@media"), TokenTkMediaSym)
		consider(l.zzLiteral(p, "@charset "), TokenTkCharsetSym)
		consider(l.zzLiteral(p, "@namespace"), TokenTkNamespaceSym)
		consider(l.zzLiteral(p, "@font-face"), TokenTkFontFaceSym)
		consider(l.zzIdent(p+1), TokenTkAtRule)
	}

	// "!"({w}|{comment})*"important"
	if c == '!' {
		consider(l.zzImportant(p), TokenTkImportantSym)
	}

	if numEnd := l.zzNum(p); numEnd >= 0 {
		for _, rule := range lexerUnitRules {
			consider(l.zzLetters(numEnd, rule.letters), rule.token)
		}
		consider(l.zzIdent(numEnd), TokenTkDimension)
		if numEnd < len(l.zzBuffer) && l.zzBuffer[numEnd] == '%' {
			consider(numEnd+1, TokenTkPercentage)
		}
		consider(numEnd, TokenTkNumber)
	}

	// "url("{w}{string}{w}")", "url("{w}{url}{w}")"
	if q := l.zzLiteral(p, "url("); q >= 0 {
		consider(l.zzURIString(q), TokenTkUri)
		consider(l.zzURIUrl(q), TokenTkUri)
	}

	// {ident}"("
	if identEnd >= 0 && identEnd < len(l.zzBuffer) && l.zzBuffer[identEnd] == '(' {
		consider(identEnd+1, TokenTkFunction)
	}

	switch c {
	case '}':
		consider(p+1, TokenTkRbrace)
	case ';':
		consider(p+1, TokenTkSemicolon)
	case '/':
		consider(p+1, TokenTkVirgule)
	case ':':
		consider(p+1, TokenTkColon)
	case '-':
		consider(p+1, TokenTkMinus)
	case ')':
		consider(p+1, TokenTkRparen)
	case '[':
		consider(p+1, TokenTkLbracket)
	case ']':
		consider(p+1, TokenTkRbracket)
	case '.':
		consider(p+1, TokenTkPeriod)
	case '=':
		consider(p+1, TokenTkEquals)
	case '*':
		consider(p+1, TokenTkAsterisk)
	case '|':
		consider(p+1, TokenTkVerticalBar)
	}

	if best < 0 {
		// .
		return p + 1, nil, true
	}
	return best, bestToken, false
}

// lexerIsSpace reports whether c is in [ \t\r\n\f].
func lexerIsSpace(c rune) bool {
	return c == ' ' || c == '\t' || c == '\r' || c == '\n' || c == '\f'
}

// lexerIsHex reports whether c is in {h}: [0-9a-fA-F].
func lexerIsHex(c rune) bool {
	return c >= '0' && c <= '9' || c >= 'a' && c <= 'f' || c >= 'A' && c <= 'F'
}

// lexerFoldEquals reports whether c matches the lower case ASCII character
// lower under %ignorecase.
func lexerFoldEquals(c rune, lower rune) bool {
	if c == lower {
		return true
	}
	if lower < 'a' || lower > 'z' {
		return false
	}
	if c == lower-('a'-'A') {
		return true
	}
	switch lower {
	case 'k':
		return c == '\u212A'
	case 's':
		return c == '\u017F'
	case 'i':
		return c == '\u0130' || c == '\u0131'
	}
	return false
}

// zzSpaceEnd returns the end of the run of [ \t\r\n\f] starting at p, which
// is p when there is none.
func (l *Lexer) zzSpaceEnd(p int) int {
	for p < len(l.zzBuffer) && lexerIsSpace(l.zzBuffer[p]) {
		p++
	}
	return p
}

// zzLiteral matches a string literal of Lexer.flex, given in lower case, at
// p. It returns the end of the match or -1.
func (l *Lexer) zzLiteral(p int, literal string) int {
	for _, lower := range literal {
		if p >= len(l.zzBuffer) || !lexerFoldEquals(l.zzBuffer[p], lower) {
			return -1
		}
		p++
	}
	return p
}

// zzComment matches comment = \/\*[^*]*\*+([^/*][^*]*\*+)*\/ at p: "/*" up to
// the first "*/". It returns the end of the match or -1.
func (l *Lexer) zzComment(p int) int {
	buf := l.zzBuffer
	if p+1 >= len(buf) || buf[p] != '/' || buf[p+1] != '*' {
		return -1
	}
	for q := p + 2; q+1 < len(buf); q++ {
		if buf[q] == '*' && buf[q+1] == '/' {
			return q + 2
		}
	}
	return -1
}

// zzNlEnd matches nl = \n|\r\n|\r|\f at p. It returns the end of the match
// or -1.
func (l *Lexer) zzNlEnd(p int) int {
	buf := l.zzBuffer
	if p >= len(buf) {
		return -1
	}
	switch buf[p] {
	case '\n', '\f':
		return p + 1
	case '\r':
		if p+1 < len(buf) && buf[p+1] == '\n' {
			return p + 2
		}
		return p + 1
	}
	return -1
}

// zzEscape matches escape = {unicode}|\\[^\r\n\f0-9a-fA-F] at p, where
// unicode = \\{h}{1,6}(\r\n|[ \t\r\n\f])?. It returns the end of the longest
// match or -1. Every rule that contains an escape continues after it in a
// way that makes the longest escape part of the longest match of the rule,
// except the url rule, which has its own matcher.
func (l *Lexer) zzEscape(p int) int {
	buf := l.zzBuffer
	if p+1 >= len(buf) || buf[p] != '\\' {
		return -1
	}
	c := buf[p+1]
	if lexerIsHex(c) {
		q := p + 1
		for q < len(buf) && q-(p+1) < 6 && lexerIsHex(buf[q]) {
			q++
		}
		if q+1 < len(buf) && buf[q] == '\r' && buf[q+1] == '\n' {
			return q + 2
		}
		if q < len(buf) && lexerIsSpace(buf[q]) {
			return q + 1
		}
		return q
	}
	if c == '\r' || c == '\n' || c == '\f' {
		return -1
	}
	return p + 2
}

// zzNmstart matches nmstart = [_a-zA-Z]|{nonascii}|{escape} at p.
func (l *Lexer) zzNmstart(p int) int {
	if p >= len(l.zzBuffer) {
		return -1
	}
	c := l.zzBuffer[p]
	if c == '_' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c > 0x7F {
		return p + 1
	}
	if c == '\\' {
		return l.zzEscape(p)
	}
	return -1
}

// zzNmchar matches nmchar = [_a-zA-Z0-9-]|{nonascii}|{escape} at p.
func (l *Lexer) zzNmchar(p int) int {
	if p >= len(l.zzBuffer) {
		return -1
	}
	c := l.zzBuffer[p]
	if c == '_' || c == '-' || c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c > 0x7F {
		return p + 1
	}
	if c == '\\' {
		return l.zzEscape(p)
	}
	return -1
}

// zzIdent matches ident = -?{nmstart}{nmchar}* at p. It returns the end of
// the longest match or -1.
func (l *Lexer) zzIdent(p int) int {
	if p < len(l.zzBuffer) && l.zzBuffer[p] == '-' {
		p++
	}
	p = l.zzNmstart(p)
	if p < 0 {
		return -1
	}
	for {
		e := l.zzNmchar(p)
		if e < 0 {
			return p
		}
		p = e
	}
}

// zzName matches name = {nmchar}+ at p. It returns the end of the longest
// match or -1.
func (l *Lexer) zzName(p int) int {
	p = l.zzNmchar(p)
	if p < 0 {
		return -1
	}
	for {
		e := l.zzNmchar(p)
		if e < 0 {
			return p
		}
		p = e
	}
}

// zzNum matches num = [0-9]+|[0-9]*"."[0-9]+ at p. It returns the end of the
// longest match or -1.
func (l *Lexer) zzNum(p int) int {
	buf := l.zzBuffer
	q := p
	for q < len(buf) && buf[q] >= '0' && buf[q] <= '9' {
		q++
	}
	if q+1 < len(buf) && buf[q] == '.' && buf[q+1] >= '0' && buf[q+1] <= '9' {
		q += 2
		for q < len(buf) && buf[q] >= '0' && buf[q] <= '9' {
			q++
		}
		return q
	}
	if q == p {
		return -1
	}
	return q
}

// zzString matches string1/string2 and invalid1/invalid2 at p, where the
// quote is. With closed it returns the end of the string. Otherwise it
// returns the end of the longest unclosed string: the scan stops before a
// line terminator, before a backslash that ends the input, or at the end of
// the input.
func (l *Lexer) zzString(p int) (end int, closed bool) {
	buf := l.zzBuffer
	quote := buf[p]
	q := p + 1
	for q < len(buf) {
		c := buf[q]
		switch {
		case c == quote:
			return q + 1, true
		case c == '\n' || c == '\r' || c == '\f':
			return q, false
		case c == '\\':
			// \\{nl}|{escape}
			e := l.zzNlEnd(q + 1)
			if e < 0 {
				e = l.zzEscape(q)
			}
			if e < 0 {
				return q, false
			}
			q = e
		default:
			q++
		}
	}
	return q, false
}

// zzLetter matches one of the letter macros of Lexer.flex (A, C, D, E, G, H,
// I, K, M, N, P, R, S, T, X, Z) at p, for example
//
//	M = m|\\0{0,4}(4d|6d)(\r\n|[ \t\r\n\f])?|\\m
//
// The hexadecimal values are the ASCII codes of the upper and lower case
// letter. The \\m alternative exists for the letters that are not
// hexadecimal digits. It returns the end of the match or -1.
func (l *Lexer) zzLetter(p int, lower rune) int {
	buf := l.zzBuffer
	if p >= len(buf) {
		return -1
	}
	if lexerFoldEquals(buf[p], lower) {
		return p + 1
	}
	if buf[p] != '\\' || p+1 >= len(buf) {
		return -1
	}
	if !lexerIsHex(lower) && lexerFoldEquals(buf[p+1], lower) {
		return p + 2
	}
	q := p + 1
	for q < len(buf) && q-(p+1) < 4 && buf[q] == '0' {
		q++
	}
	if q+1 >= len(buf) || !lexerIsHex(buf[q]) || !lexerIsHex(buf[q+1]) {
		return -1
	}
	value := rune(lexerHexValue(buf[q])<<4 | lexerHexValue(buf[q+1]))
	if value != lower && value != lower-('a'-'A') {
		return -1
	}
	q += 2
	if q+1 < len(buf) && buf[q] == '\r' && buf[q+1] == '\n' {
		return q + 2
	}
	if q < len(buf) && lexerIsSpace(buf[q]) {
		return q + 1
	}
	return q
}

func lexerHexValue(c rune) int {
	switch {
	case c >= '0' && c <= '9':
		return int(c - '0')
	case c >= 'a' && c <= 'f':
		return int(c-'a') + 10
	default:
		return int(c-'A') + 10
	}
}

// zzLetters matches a sequence of letter macros at p. It returns the end of
// the match or -1.
func (l *Lexer) zzLetters(p int, letters string) int {
	for _, lower := range letters {
		p = l.zzLetter(p, lower)
		if p < 0 {
			return -1
		}
	}
	return p
}

// zzImportant matches "!"({w}|{comment})*"important" at p, where the "!" is.
// It returns the end of the match or -1.
func (l *Lexer) zzImportant(p int) int {
	q := p + 1
	for {
		q = l.zzSpaceEnd(q)
		e := l.zzComment(q)
		if e < 0 {
			break
		}
		q = e
	}
	return l.zzLiteral(q, "important")
}

// zzURIString matches {w}{string}{w}")" at p, the position after "url(". It
// returns the end of the match or -1.
func (l *Lexer) zzURIString(p int) int {
	buf := l.zzBuffer
	q := l.zzSpaceEnd(p)
	if q >= len(buf) || buf[q] != '"' && buf[q] != '\'' {
		return -1
	}
	e, closed := l.zzString(q)
	if !closed {
		return -1
	}
	q = l.zzSpaceEnd(e)
	if q < len(buf) && buf[q] == ')' {
		return q + 1
	}
	return -1
}

// lexerIsURLChar reports whether c is in [!#$%&*-~] or is {nonascii}. The
// range *-~ contains the backslash.
func lexerIsURLChar(c rune) bool {
	return c == '!' || c == '#' || c == '$' || c == '%' || c == '&' || c >= '*' && c <= '~' || c > 0x7F
}

// zzURIUrl matches {w}{url}{w}")" at p, the position after "url(", where
// url = ([!#$%&*-~]|{nonascii}|{escape})*. It returns the end of the longest
// match or -1.
//
// A backslash is both a url character and the start of an escape, and the
// white space after a hexadecimal escape is optional, so one input can be
// read in several ways that end at different positions. The matcher follows
// all of them: reachable holds the positions, relative to the start of the
// url, at which the url part can end.
func (l *Lexer) zzURIUrl(p int) int {
	buf := l.zzBuffer
	start := l.zzSpaceEnd(p)
	best := -1
	reachable := []bool{true}
	mark := func(q int) {
		i := q - start
		for len(reachable) <= i {
			reachable = append(reachable, false)
		}
		reachable[i] = true
	}
	for i := 0; i < len(reachable); i++ {
		if !reachable[i] {
			continue
		}
		q := start + i

		// {w}")"
		if e := l.zzSpaceEnd(q); e < len(buf) && buf[e] == ')' {
			if e+1 > best {
				best = e + 1
			}
		}

		if q >= len(buf) {
			continue
		}
		c := buf[q]
		if lexerIsURLChar(c) {
			mark(q + 1)
		}
		if c != '\\' || q+1 >= len(buf) {
			continue
		}
		next := buf[q+1]
		if !lexerIsHex(next) {
			if next != '\r' && next != '\n' && next != '\f' {
				mark(q + 2)
			}
			continue
		}
		// unicode = \\{h}{1,6}(\r\n|[ \t\r\n\f])?
		for h := q + 1; h < len(buf) && h-(q+1) < 6 && lexerIsHex(buf[h]); h++ {
			after := h + 1
			mark(after)
			if after < len(buf) && lexerIsSpace(buf[after]) {
				mark(after + 1)
				if buf[after] == '\r' && after+1 < len(buf) && buf[after+1] == '\n' {
					mark(after + 2)
				}
			}
		}
	}
	return best
}
