// Ported from flying-saucer-core/src/main/java/org/xhtmlrenderer/css/parser/property/Conversions.java

package ufo

var conversionsColors = map[string]*FSRGBColor{
	"cyan":                 NewFSRGBColorInt(0x00FFFF),
	"magenta":              NewFSRGBColorInt(0xFF00FF),
	"black":                NewFSRGBColorInt(0x000000),
	"gray":                 NewFSRGBColorInt(0x808080),
	"grey":                 NewFSRGBColorInt(0x808080),
	"maroon":               NewFSRGBColorInt(0x800000),
	"red":                  NewFSRGBColorInt(0xFF0000),
	"green":                NewFSRGBColorInt(0x008000),
	"lime":                 NewFSRGBColorInt(0x00FF00),
	"olive":                NewFSRGBColorInt(0x808000),
	"yellow":               NewFSRGBColorInt(0xFFFF00),
	"navy":                 NewFSRGBColorInt(0x000080),
	"blue":                 NewFSRGBColorInt(0x0000FF),
	"purple":               NewFSRGBColorInt(0x800080),
	"fuchsia":              NewFSRGBColorInt(0xFF00FF),
	"teal":                 NewFSRGBColorInt(0x008080),
	"aqua":                 NewFSRGBColorInt(0x00FFFF),
	"silver":               NewFSRGBColorInt(0xC0C0C0),
	"white":                NewFSRGBColorInt(0xFFFFFF),
	"aliceblue":            NewFSRGBColorInt(0xF0F8FF),
	"antiquewhite":         NewFSRGBColorInt(0xFAEBD7),
	"aquamarine":           NewFSRGBColorInt(0x7FFFD4),
	"azure":                NewFSRGBColorInt(0xF0FFFF),
	"beige":                NewFSRGBColorInt(0xF5F5DC),
	"blueviolet":           NewFSRGBColorInt(0x8A2BE2),
	"brown":                NewFSRGBColorInt(0xA52A2A),
	"burlywood":            NewFSRGBColorInt(0xDEB887),
	"cadetblue":            NewFSRGBColorInt(0x5F9EA0),
	"chartreuse":           NewFSRGBColorInt(0x7FFF00),
	"chocolate":            NewFSRGBColorInt(0xD2691E),
	"coral":                NewFSRGBColorInt(0xFF7F50),
	"cornflowerblue":       NewFSRGBColorInt(0x6495ED),
	"cornsilk":             NewFSRGBColorInt(0xFFF8DC),
	"crimson":              NewFSRGBColorInt(0xDC143C),
	"darkblue":             NewFSRGBColorInt(0x00008B),
	"darkcyan":             NewFSRGBColorInt(0x008B8B),
	"darkgoldenrod":        NewFSRGBColorInt(0xB8860B),
	"darkgray":             NewFSRGBColorInt(0xA9A9A9),
	"darkgreen":            NewFSRGBColorInt(0x006400),
	"darkkhaki":            NewFSRGBColorInt(0xBDB76B),
	"darkmagenta":          NewFSRGBColorInt(0x8B008B),
	"darkolivegreen":       NewFSRGBColorInt(0x556B2F),
	"darkorange":           NewFSRGBColorInt(0xFF8C00),
	"darkorchid":           NewFSRGBColorInt(0x9932CC),
	"darkred":              NewFSRGBColorInt(0x8B0000),
	"darksalmon":           NewFSRGBColorInt(0xE9967A),
	"darkseagreen":         NewFSRGBColorInt(0x8FBC8F),
	"darkslateblue":        NewFSRGBColorInt(0x483D8B),
	"darkslategray":        NewFSRGBColorInt(0x2F4F4F),
	"darkturquoise":        NewFSRGBColorInt(0x00CED1),
	"darkviolet":           NewFSRGBColorInt(0x9400D3),
	"deeppink":             NewFSRGBColorInt(0xFF1493),
	"deepskyblue":          NewFSRGBColorInt(0x00BFFF),
	"dimgray":              NewFSRGBColorInt(0x696969),
	"dodgerblue":           NewFSRGBColorInt(0x1E90FF),
	"firebrick":            NewFSRGBColorInt(0xB22222),
	"floralwhite":          NewFSRGBColorInt(0xFFFAF0),
	"forestgreen":          NewFSRGBColorInt(0x228B22),
	"gainsboro":            NewFSRGBColorInt(0xDCDCDC),
	"ghostwhite":           NewFSRGBColorInt(0xF8F8FF),
	"gold":                 NewFSRGBColorInt(0xFFD700),
	"goldenrod":            NewFSRGBColorInt(0xDAA520),
	"greenyellow":          NewFSRGBColorInt(0xADFF2F),
	"honeydew":             NewFSRGBColorInt(0xF0FFF0),
	"hotpink":              NewFSRGBColorInt(0xFF69B4),
	"indianred":            NewFSRGBColorInt(0xCD5C5C),
	"indigo":               NewFSRGBColorInt(0x4B0082),
	"ivory":                NewFSRGBColorInt(0xFFFFF0),
	"khaki":                NewFSRGBColorInt(0xF0E68C),
	"lavender":             NewFSRGBColorInt(0xE6E6FA),
	"lavenderblush":        NewFSRGBColorInt(0xFFF0F5),
	"lawngreen":            NewFSRGBColorInt(0x7CFC00),
	"lemonchiffon":         NewFSRGBColorInt(0xFFFACD),
	"lightblue":            NewFSRGBColorInt(0xADD8E6),
	"lightcoral":           NewFSRGBColorInt(0xF08080),
	"lightcyan":            NewFSRGBColorInt(0xE0FFFF),
	"lightgoldenrodyellow": NewFSRGBColorInt(0xFAFAD2),
	"lightgreen":           NewFSRGBColorInt(0x90EE90),
	"lightgrey":            NewFSRGBColorInt(0xD3D3D3),
	"lightpink":            NewFSRGBColorInt(0xFFB6C1),
	"lightsalmon":          NewFSRGBColorInt(0xFFA07A),
	"lightseagreen":        NewFSRGBColorInt(0x20B2AA),
	"lightskyblue":         NewFSRGBColorInt(0x87CEFA),
	"lightslategray":       NewFSRGBColorInt(0x778899),
	"lightsteelblue":       NewFSRGBColorInt(0xB0C4DE),
	"lightyellow":          NewFSRGBColorInt(0xFFFFE0),
	"limegreen":            NewFSRGBColorInt(0x32CD32),
	"linen":                NewFSRGBColorInt(0xFAF0E6),
	"mediumaquamarine":     NewFSRGBColorInt(0x66CDAA),
	"mediumblue":           NewFSRGBColorInt(0x0000CD),
	"mediumorchid":         NewFSRGBColorInt(0xBA55D3),
	"mediumpurple":         NewFSRGBColorInt(0x9370DB),
	"mediumseagreen":       NewFSRGBColorInt(0x3CB371),
	"mediumslateblue":      NewFSRGBColorInt(0x7B68EE),
	"mediumspringgreen":    NewFSRGBColorInt(0x00FA9A),
	"mediumturquoise":      NewFSRGBColorInt(0x48D1CC),
	"mediumvioletred":      NewFSRGBColorInt(0xC71585),
	"midnightblue":         NewFSRGBColorInt(0x191970),
	"mintcream":            NewFSRGBColorInt(0xF5FFFA),
	"mistyrose":            NewFSRGBColorInt(0xFFE4E1),
	"moccasin":             NewFSRGBColorInt(0xFFE4B5),
	"navajowhite":          NewFSRGBColorInt(0xFFDEAD),
	"oldlace":              NewFSRGBColorInt(0xFDF5E6),
	"olivedrab":            NewFSRGBColorInt(0x6B8E23),
	"orange":               NewFSRGBColorInt(0xFFA500),
	"orangered":            NewFSRGBColorInt(0xFF4500),
	"orchid":               NewFSRGBColorInt(0xDA70D6),
	"palegoldenrod":        NewFSRGBColorInt(0xEEE8AA),
	"palegreen":            NewFSRGBColorInt(0x98FB98),
	"paleturquoise":        NewFSRGBColorInt(0xAFEEEE),
	"palevioletred":        NewFSRGBColorInt(0xDB7093),
	"papayawhip":           NewFSRGBColorInt(0xFFEFD5),
	"peachpuff":            NewFSRGBColorInt(0xFFDAB9),
	"peru":                 NewFSRGBColorInt(0xCD853F),
	"pink":                 NewFSRGBColorInt(0xFFC0CB),
	"plum":                 NewFSRGBColorInt(0xDDA0DD),
	"powderblue":           NewFSRGBColorInt(0xB0E0E6),
	"rosybrown":            NewFSRGBColorInt(0xBC8F8F),
	"royalblue":            NewFSRGBColorInt(0x4169E1),
	"saddlebrown":          NewFSRGBColorInt(0x8B4513),
	"salmon":               NewFSRGBColorInt(0xFA8072),
	"sandybrown":           NewFSRGBColorInt(0xF4A460),
	"seagreen":             NewFSRGBColorInt(0x2E8B57),
	"seashell":             NewFSRGBColorInt(0xFFF5EE),
	"sienna":               NewFSRGBColorInt(0xA0522D),
	"skyblue":              NewFSRGBColorInt(0x87CEEB),
	"slateblue":            NewFSRGBColorInt(0x6A5ACD),
	"slategray":            NewFSRGBColorInt(0x708090),
	"snow":                 NewFSRGBColorInt(0xFFFAFA),
	"springgreen":          NewFSRGBColorInt(0x00FF7F),
	"steelblue":            NewFSRGBColorInt(0x4682B4),
	"tan":                  NewFSRGBColorInt(0xD2B48C),
	"thistle":              NewFSRGBColorInt(0xD8BFD8),
	"tomato":               NewFSRGBColorInt(0xFF6347),
	"turquoise":            NewFSRGBColorInt(0x40E0D0),
	"violet":               NewFSRGBColorInt(0xEE82E),
	"wheat":                NewFSRGBColorInt(0xF5DEB3),
	"whitesmoke":           NewFSRGBColorInt(0xF5F5F5),
	"yellowgreen":          NewFSRGBColorInt(0x9ACD32),
}

var conversionsNumericFontWeights = map[float32]*IdentValue{
	100.0: IdentValueFontWeight100,
	200.0: IdentValueFontWeight200,
	300.0: IdentValueFontWeight300,
	400.0: IdentValueFontWeight400,
	500.0: IdentValueFontWeight500,
	600.0: IdentValueFontWeight600,
	700.0: IdentValueFontWeight700,
	800.0: IdentValueFontWeight800,
	900.0: IdentValueFontWeight900,
}

var conversionsBorderWidths = map[string]*PropertyValue{
	"thin":   NewPropertyValueFloat(CSSPrimitiveValueCssPx, 1.0, "1px"),
	"medium": NewPropertyValueFloat(CSSPrimitiveValueCssPx, 2.0, "2px"),
	"thick":  NewPropertyValueFloat(CSSPrimitiveValueCssPx, 3.0, "3px"),
}

// ConversionsGetColor returns nil when ident is not a color name.
func ConversionsGetColor(ident string) *FSRGBColor {
	return conversionsColors[ident]
}

// ConversionsGetNumericFontWeight returns nil when weight is not one of the
// nine numeric font weights.
func ConversionsGetNumericFontWeight(weight float32) *IdentValue {
	return conversionsNumericFontWeights[weight]
}

func ConversionsGetBorderWidth(ident string) *PropertyValue {
	return conversionsBorderWidths[ident]
}
