// Ported from flying-saucer-core/src/test/java/org/xhtmlrenderer/util/ContentTypeDetectingInputStreamWrapperTest.java

package ufo

import (
	"bytes"
	"io"
	"strings"
	"testing"
)

var contentTypeDetectingTestBom = []byte{0xEF, 0xBB, 0xBF}

func contentTypeDetectingTestStream(t *testing.T, data []byte) *ContentTypeDetectingInputStreamWrapper {
	t.Helper()
	stream, err := ContentTypeDetectingInputStreamWrapperDetectContentType(bytes.NewReader(data))
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { stream.Close() })
	return stream
}

func checkContentTypeDetecting(t *testing.T, data []byte, wantPdf, wantSvg bool) {
	t.Helper()
	stream := contentTypeDetectingTestStream(t, data)
	if got := stream.IsPdf(); got != wantPdf {
		t.Errorf("IsPdf() = %t, want %t", got, wantPdf)
	}
	got, err := stream.IsSvg()
	if err != nil {
		t.Fatal(err)
	}
	if got != wantSvg {
		t.Errorf("IsSvg() = %t, want %t", got, wantSvg)
	}
}

func TestContentTypeDetectingInputStreamWrapperIsPdf(t *testing.T) {
	checkContentTypeDetecting(t, []byte("%PDF1234567890"), true, false)
}

func TestContentTypeDetectingInputStreamWrapperIsNotPdf(t *testing.T) {
	checkContentTypeDetecting(t, []byte("Hello, world"), false, false)
}

func TestContentTypeDetectingInputStreamWrapperIsSvg(t *testing.T) {
	checkContentTypeDetecting(t, []byte(`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg><metadata id="metadata367"><rdf:RDF>
`), false, true)
}

func TestContentTypeDetectingInputStreamWrapperIsSvg_withoutXmlHeader(t *testing.T) {
	checkContentTypeDetecting(t, []byte(`<svg><metadata id="metadata367"><rdf:RDF>
`), false, true)
}

// Real-world regression: SVGs saved by text editors that auto-prepend a
// UTF-8 BOM (Notepad on Windows, some Vim configs) start with the bytes
// EF BB BF before the <?xml or <svg header. Without BOM-skipping, firstBytes
// captures EF BB BF 3C and the byte-exact magic comparison against "<?xm" /
// "<svg" fails, so a valid SVG fails type detection and downstream SVG
// loading is skipped.
func TestContentTypeDetectingInputStreamWrapperIsSvg_withUtf8Bom(t *testing.T) {
	streamBytes := append(bytes.Clone(contentTypeDetectingTestBom), "<svg><metadata/></svg>"...)
	checkContentTypeDetecting(t, streamBytes, false, true)
}

func TestContentTypeDetectingInputStreamWrapperIsSvg_withUtf8Bom_andXmlHeader(t *testing.T) {
	streamBytes := append(bytes.Clone(contentTypeDetectingTestBom), `<?xml version="1.0"?><svg/>`...)
	checkContentTypeDetecting(t, streamBytes, false, true)
}

// Real-world regression: some tools comment out the XML declaration before
// emitting the real one (or omit it entirely), so the file's first bytes are
// a comment rather than <?xml / <svg.
func TestContentTypeDetectingInputStreamWrapperIsSvg_withLeadingComment(t *testing.T) {
	checkContentTypeDetecting(t, []byte(`<!--<?xml version="1.0" encoding="UTF-8" standalone="no"?>-->
<svg><metadata id="metadata367"><rdf:RDF>
`), false, true)
}

// Strictly, an XML declaration must be the very first thing in the document:
// nothing, not even a comment, may precede <?xml, so this input isn't
// well-formed XML. We detect it as SVG anyway: this class is a lenient
// best-effort sniffer, not a conformance checker, and an actually malformed
// file still fails later at the real parse.
func TestContentTypeDetectingInputStreamWrapperIsSvg_withLeadingCommentAndXmlHeader(t *testing.T) {
	checkContentTypeDetecting(t, []byte(`<!-- generated by some tool -->
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg><metadata id="metadata367"><rdf:RDF>
`), false, true)
}

func TestContentTypeDetectingInputStreamWrapperIsSvg_withMultipleLeadingComments(t *testing.T) {
	checkContentTypeDetecting(t, []byte(`<!-- first comment -->
<!-- second comment -->
<svg/>
`), false, true)
}

// source may be attacker-controlled (a remote URL referenced from untrusted
// HTML/CSS), so the leading-comment scan is capped rather than unbounded:
// otherwise a comment that never closes would let the underlying buffer grow
// for as long as bytes keep arriving. Exceeding the cap returns an error
// instead of silently misdetecting; the stream must still come back fully
// intact afterward for whatever reads the SVG body next.
func TestContentTypeDetectingInputStreamWrapperIsSvg_throwsWhenLeadingCommentExceedsScanLimit(t *testing.T) {
	streamBytes := []byte("<!--" + strings.Repeat("x", 10_000) + "-->\n<svg/>\n")

	stream := contentTypeDetectingTestStream(t, streamBytes)
	if _, err := stream.IsSvg(); err == nil {
		t.Errorf("IsSvg() returned no error")
	}
	rest, err := io.ReadAll(stream)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(rest, streamBytes) {
		t.Errorf("the stream yields %d bytes after the failed scan, want the %d bytes of the source", len(rest), len(streamBytes))
	}
}

func TestContentTypeDetectingInputStreamWrapperIsSvg_withUnterminatedComment(t *testing.T) {
	checkContentTypeDetecting(t, []byte("<!-- never closed <svg/>"), false, false)
}

func TestContentTypeDetectingInputStreamWrapperDetectContentTypeOfNil(t *testing.T) {
	stream, err := ContentTypeDetectingInputStreamWrapperDetectContentType(nil)
	if stream != nil || err != nil {
		t.Errorf("got %v, %v for a nil stream, want nil, nil", stream, err)
	}
}

func TestContentTypeDetectingInputStreamWrapperShortStream(t *testing.T) {
	checkContentTypeDetecting(t, []byte("<s"), false, false)
	checkContentTypeDetecting(t, []byte{}, false, false)
}
